spring.application.name=media_backlog_api

# Names temporary database
spring.datasource.url=jdbc:h2:mem:mediadb

# Turns on the web based database viewer
spring.h2.console.enabled=true

# Tells JPA to auto-create our sql tables based on our Java Classes
spring.jpa.hibernate.ddl-auto=update